version: '3'
services:
  app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: npm run test

  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: user_db
      POSTGRES_DB: cats_db
      POSTGRES_PORT: 5432
